### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by MarcinOrlowski** [meNESS/TimelinePostContainer#5]
If you wonder why your library has very little stars and forks I come to the rescue -> your description lack screenshots/gifs and/or downloadable demo APK. Welcome :)

**Comment by meNESS** [comment]
@MarcinOrlowski Thanks sir. I'm currently working on a new library, [EasyIntro](https://github.com/meNESS/EasyIntro) and sometimes just update this one but I will work on making better documentation and some samples. Thanks again.
